### ISSUE TITLE
Add guidance on image file formats and resolutions suitable for different purposes

### ISSUE THREAD

**Issue by gcapes** [LightForm-group/non-repo-issues#10]
papers, presentations etc

**Comment by gcapes** [comment]
I found this https://btjanaka.net/blog/matplotlib-figures/ which I could summarise on the wiki and then link to. What do we think?

**Comment by JQFonseca** [comment]
This is a good start. I think we also need to add a bit for microscope
images, EBSD maps etc. Happy to add to it if you get it started!

**Comment by gcapes** [comment]
Great - I've added the stuff on general python images. Do we need a separate issue for the other types of image you mentioned?

**Comment by JQFonseca** [comment]
Go on and assign it to me.
