### ISSUE TITLE
Proposals for MatFlow documentation

### ISSUE THREAD

**Issue by cjfullerton** [LightForm-group/non-repo-issues#17]
We need some proposals for the kind of documentation that MatFlow needs.

Let's come up with a shortlist and then we can do some prioritisation.

Suggestions in the comments.

**Comment by gcapes** [comment]
- [x] How to use built-in workflows. What workflows are there, how do you find out, and what do they do?
- [x] How to write your own workflow. This should probably be part tutorial, and part documentation of what each key word in a workflow means, what level it applies to, how to use outputs/files from one task in a later task
- [x] Common errors and 'gotchas', particularly resulting from updating Matflow to a newer version

**Comment by gcapes** [comment]
See also https://github.com/LightForm-group/non-repo-issues/issues/14
