### ISSUE TITLE
Contact students and postdocs to get an idea of what they need help with

### ISSUE THREAD

**Issue by cjfullerton** [LightForm-group/non-repo-issues#18]
We have a list of students and PDRAs that @JQFonseca suggests needs some assistance with MatFlow development:

- [x] #23 
- [x] #20
- [x] #21 
- [x] Rory Barker
- [x] #24 

Get in touch with them, work out what they need and create some more issues to capture it.

**Comment by gcapes** [comment]
Meeting scheduled with Patrick for 11 June.

**Comment by gcapes** [comment]
Initial messages sent to all students, requesting a scoping chat.

**Comment by gcapes** [comment]
Met Yuchen and Sam today. Meeting Laura Friday 7th.
