### ISSUE TITLE
Setup recurring meeting with Adam

### ISSUE THREAD

**Issue by cjfullerton** [LightForm-group/non-repo-issues#22]

**Comment by gcapes** [comment]
Meeting on Friday. Discuss:

- [x] https://github.com/LightForm-group/matflow-user-documentation/issues/3
- [x] https://github.com/LightForm-group/matflow-user-documentation/issues/8
- [x] https://github.com/LightForm-group/non-repo-issues/issues/25
- [x] Which version(s) of matflow does the current "matflow environments" artifact work with?
- [x] When does `~/.matflow-new` get created?
- [x] Are there any shortcuts for creating an environment file for CSF3?
- [x] Can you have multiple environment files, and if so is there a heirarchy?
- [x] https://github.com/LightForm-group/non-repo-issues/issues/21
- [x] common "gotchas" when using a newer/older version. Release notes don't seem to go into much detail e.g. format of resource block

**Comment by gcapes** [comment]
Current matflow envs only guaranteed to work with latest matflow.

**Comment by gcapes** [comment]
`~/.matflow-new` is created when you first run matflow, however it's been installed.

**Comment by gcapes** [comment]
https://docs.matflow.io/stable/user/how_to/environments.html
Duplicate environments will raise an exception.

**Comment by gcapes** [comment]
Look at demo workflows for current format.
