### ISSUE TITLE
Put together an overview presentation of GitHub projects/Agile/Scrum

### ISSUE THREAD

**Issue by gcapes** [LightForm-group/non-repo-issues#29]
This would be for MatFlow users (PhD students) to plan their work and request help through tagging a person on an issue, but also for others to be able to track MatFlow issues "at a glance".

**Comment by Gbowker** [comment]
Hi @gcapes, I look forward to helping with/attending this.

Commenting here to get the hang of using this!

**Comment by gcapes** [comment]
Great that there's already some interest in this :smile:

**Comment by gcapes** [comment]
I met with Guy yesterday to give a quick overview of Agile/Scrum/how I use the GH project boards. He suggested this might be good to talk about/demo at one of the modelling meetings. Should I perhaps aim to put some notes together to evangelise about version control and Agile project management at the next meeting (26 Nov)? @JQFonseca

**Comment by gcapes** [comment]
Let's aim for the following meeting (17th December)

**Comment by Gbowker** [comment]
Great! And we can make it  ❄️ 🎁 🎄 🤶  _christmas themed!_ 🎅 🎄 🎁 ❄️
I'll book a meeting room today.

**Comment by gcapes** [comment]
Ok, I've put together a bit of a rough and ready set of notes for this, and along with an unrehearsed demo it might take 5-10 mins. I think we can do this in the next meeting (26 Nov). @JQFonseca is also around for that meeting so it might be better as he can add to what I've said from his perspective.
Shall we go for that and maybe @JQFonseca do you want to "advertise" the fact that this will be happening? I'm happy to do that if you'd rather.

**Comment by Gbowker** [comment]
Ok, we have the larger meeting room 1.015 for this (if nobody kicks us out for a more impoprtant meeting) I'll get a short demo together to show the benefits of version control for writing aswell. @samuel-hg-engel said he was onboard to show how he has created python packages and version controlled them with Git. Would you like to do this @samuel-hg-engel ?

**Comment by JQFonseca** [comment]
Hi Gerard,

Please go ahead. I will reinforce your message.

João

**Comment by gcapes** [comment]
Slack messages sent, and reinforced by Joao.
