### ISSUE TITLE
Host code on GitHub and link from new wiki section on steel modelling

### ISSUE THREAD

**Issue by gcapes** [LightForm-group/non-repo-issues#3]
This is for Josh Collins.
Have asked for more details - waiting to hear back.
Met with Josh, and guided him through putting code on GitHub in a python module instead of notebook, and linking from a new wiki section. He is now in a position complete the task himself for another set of code.
Sent details about upcoming version control course on git.

**Comment by JQFonseca** [comment]
I don't know Josh Collins. He is not in LightForm?

**Comment by gcapes** [comment]
No, I don't think he's in LightForm - the work came via @aplowman
