### ISSUE TITLE
Check demo workflow "RVE_extrusion_EBSD"

### ISSUE THREAD

**Issue by gcapes** [LightForm-group/non-repo-issues#30]
Patrick has had trouble with a workflow derived from this. It works using Matflow  0.3.0a110, but not the latest.
I'm going to test the demo workflow and go from there.

**Comment by gcapes** [comment]
I have now tested this with MatFlow, version 0.3.0a132 in a new venv, with latest defdap, damask_parse and formable packages. The error comes in the first task 
<pre>┌────┬──────────────────────────────────────┬──────────┬────────────────────────────┬─────────────────────────────────────────────────────┐
│<b> ID </b>│<b> Name                                 </b>│<b> Status   </b>│<b> Times                      </b>│<b> Actions                                             </b>│
├────┼──────────────────────────────────────┼──────────┼────────────────────────────┼─────────────────────────────────────────────────────┤
│ 54 │ RVE_extrusion_EBSD_2024-11-25_102941 │ <font color="#767676">◊</font>/<font color="#0087FF">●</font>      │  <i>sb.</i>  2024-11-25 10:29:47  │  load_microstructure_EBSD            0 | <font color="#D70000">E</font>          │
│    │                                      │          │  <i>st.</i>             10:49:36  │  generate_volume_element_extrusion   0 | <font color="#FF8700">s</font>          │
│    │                                      │          │  <i>en.</i>             10:58:02  │  visualise_VE_VTK_1                  0 | <font color="#0087FF">●</font>          │
│    │                                      │          │                            │  modify_VE_add_buffer_zones          0 | <font color="#767676">.</font>          │
│    │                                      │          │                            │  visualise_VE_VTK_2                  0 | <font color="#767676">.</font>          │
│    │                                      │          │                            │  simulate_VE_loading_damask          0 | <font color="#767676">........</font>   │
│    │                                      │          │                            │                                                     │
</pre>

<pre>cat artifacts/submissions/0/js_0.sh.e5290224 
Traceback (most recent call last):
  File &quot;/net/scratch2/mbexegc2/patrick_curran/RVE_extrusion_EBSD_2024-11-25_102941/execute/task_0_load_microstructure_EBSD/e_0/r_0/load_microstructure_EBSD.py&quot;, line 233, in &lt;module&gt;
    outputs = load_microstructure_EBSD(**direct_ins)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File &quot;/net/scratch2/mbexegc2/patrick_curran/RVE_extrusion_EBSD_2024-11-25_102941/execute/task_0_load_microstructure_EBSD/e_0/r_0/load_microstructure_EBSD.py&quot;, line 24, in load_microstructure_EBSD
    EBSD_image = get_EBSD_image(ebsd_map, scaling_factor)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File &quot;/net/scratch2/mbexegc2/patrick_curran/RVE_extrusion_EBSD_2024-11-25_102941/execute/task_0_load_microstructure_EBSD/e_0/r_0/load_microstructure_EBSD.py&quot;, line 67, in get_EBSD_image
    remove_small_grain_points(grain_image)
  File &quot;/net/scratch2/mbexegc2/patrick_curran/RVE_extrusion_EBSD_2024-11-25_102941/execute/task_0_load_microstructure_EBSD/e_0/r_0/load_microstructure_EBSD.py&quot;, line 194, in remove_small_grain_points
    for mode_val, mode_count in zip(mode_vals, mode_counts):
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: &apos;numpy.int64&apos; object is not iterable
</pre>

**Comment by aplowman** [comment]
I think it works if you fix the versions of numpy, scipy and defdap as listed here: https://github.com/hpcflow/matflow-environments/blob/main/defdap_env/environment.yaml

**Comment by gcapes** [comment]
Thanks, I'll give that a try. If successful, I guess I should create a copy of this issue in the defdap repo?

**Comment by gcapes** [comment]
When updating the versions in the venv, I get this

<pre><font color="#CC0000">ERROR: pip&apos;s dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.</font>
<font color="#CC0000">numcodecs 0.14.1 requires numpy&gt;=1.24, but you have numpy 1.23.5 which is incompatible.</font>
<font color="#CC0000">hpcflow-new2 0.2.0a181 requires numpy&lt;2.0.0,&gt;=1.26.4; python_version &gt;= &quot;3.9&quot;, but you have numpy 1.23.5 which is incompatible.</font>
<font color="#CC0000">damask-parse 0.2.30 requires numpy&gt;=1.26.4; python_version &gt;= &quot;3.9&quot;, but you have numpy 1.23.5 which is incompatible.</font>
<font color="#CC0000">damask-parse 0.2.30 requires scipy&gt;=1.13.0; python_version &gt;= &quot;3.9&quot;, but you have scipy 1.10.1 which is incompatible.</font>
Successfully installed defdap-0.93.4 numpy-1.23.5 scipy-1.10.1
</pre>

**Comment by gcapes** [comment]
It seems that you can ignore that error and submit the job anyway.

Need to re-test this thoroughly checking the config/envs etc to find out what does and doesn't work

**Comment by gcapes** [comment]
I've reproduced my original set of errors given here https://github.com/LightForm-group/non-repo-issues/issues/30#issuecomment-2498117282
This uses the latest version of all packages, including numpy  version 1.26.4

<pre>┌────┬─────────────────┬──────────┬────────────────────────────┬─────────────────────────────────────────────────────┐
│<b> ID </b>│<b> Name            </b>│<b> Status   </b>│<b> Times                      </b>│<b> Actions                                             </b>│
├────┼─────────────────┼──────────┼────────────────────────────┼─────────────────────────────────────────────────────┤
│ <font color="#6C6C6C">1 </font> │ <font color="#6C6C6C">latest_versions</font> │ <font color="#6C6C6C"><i>inactive</i></font> │  <font color="#6C6C6C"><i>sb.</i></font>  <font color="#6C6C6C">2024-11-28 11:17:41</font>  │ <font color="#6C6C6C"> load_microstructure_EBSD            0 | </font><font color="#D70000">E</font><font color="#6C6C6C">         </font> │
│    │                 │          │  <font color="#6C6C6C"><i>st.</i></font>  <font color="#6C6C6C">           11:17:43</font>  │ <font color="#6C6C6C"> generate_volume_element_extrusion   0 | </font><font color="#FF8700">s</font><font color="#6C6C6C">         </font> │
│    │                 │          │  <font color="#6C6C6C"><i>en.</i></font>  <font color="#6C6C6C">           11:19:32</font>  │ <font color="#6C6C6C"> visualise_VE_VTK_1                  0 | </font><font color="#D70000">E</font><font color="#6C6C6C">         </font> │
│    │                 │          │                            │ <font color="#6C6C6C"> modify_VE_add_buffer_zones          0 | </font><font color="#D70000">E</font><font color="#6C6C6C">         </font> │
│    │                 │          │                            │ <font color="#6C6C6C"> visualise_VE_VTK_2                  0 | </font><font color="#FF8700">s</font><font color="#6C6C6C">         </font> │
│    │                 │          │                            │ <font color="#6C6C6C"> simulate_VE_loading_damask          0 | </font><font color="#FF8700">s</font><font color="#00D700">■</font><font color="#FF8700">s</font><font color="#00D700">■</font><font color="#D70000">E</font><font color="#FF8700">sss</font><font color="#6C6C6C">  </font> │
</pre>

```
cat artifacts/submissions/0/js_0.sh.e5309668 
Traceback (most recent call last):
  File "/net/scratch2/mbexegc2/patrick_curran/latest_versions/execute/task_0_load_microstructure_EBSD/e_0/r_0/load_microstructure_EBSD.py", line 233, in <module>
    outputs = load_microstructure_EBSD(**direct_ins)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/net/scratch2/mbexegc2/patrick_curran/latest_versions/execute/task_0_load_microstructure_EBSD/e_0/r_0/load_microstructure_EBSD.py", line 24, in load_microstructure_EBSD
    EBSD_image = get_EBSD_image(ebsd_map, scaling_factor)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/net/scratch2/mbexegc2/patrick_curran/latest_versions/execute/task_0_load_microstructure_EBSD/e_0/r_0/load_microstructure_EBSD.py", line 67, in get_EBSD_image
    remove_small_grain_points(grain_image)
  File "/net/scratch2/mbexegc2/patrick_curran/latest_versions/execute/task_0_load_microstructure_EBSD/e_0/r_0/load_microstructure_EBSD.py", line 194, in remove_small_grain_points
    for mode_val, mode_count in zip(mode_vals, mode_counts):
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'numpy.int64' object is not iterable
```

So this looks to be something fixable within the MatFlow code, related to maybe something deprecated in numpy.

I created an issue for that https://github.com/hpcflow/matflow-new/issues/266

**Comment by gcapes** [comment]
Next, fixing the versions as Adam suggested, to 

      - numpy==1.23.5
      - scipy==1.10.1
      - matflow-new
      - defdap==0.93.4

does indeed give an error from pip about incompatible numpy version requirements from different packages. https://github.com/LightForm-group/non-repo-issues/issues/30#issuecomment-2498216198

That said, if you ignore this error and continue, the workflow runs most of the way through:


<pre>┌────┬─────────────────────┬──────────┬────────────────────────────┬─────────────────────────────────────────────────────┐
│<b> ID </b>│<b> Name                </b>│<b> Status   </b>│<b> Times                      </b>│<b> Actions                                             </b>│
├────┼─────────────────────┼──────────┼────────────────────────────┼─────────────────────────────────────────────────────┤
│ <font color="#6C6C6C">2 </font> │ <font color="#6C6C6C">restricted_versions</font> │ <font color="#6C6C6C"><i>inactive</i></font> │  <font color="#6C6C6C"><i>sb.</i></font>  <font color="#6C6C6C">2024-11-28 11:48:09</font>  │ <font color="#6C6C6C"> load_microstructure_EBSD            0 | </font><font color="#00D700">■</font><font color="#6C6C6C">         </font> │
│    │                     │          │  <font color="#6C6C6C"><i>st.</i></font>  <font color="#6C6C6C">           11:48:19</font>  │ <font color="#6C6C6C"> generate_volume_element_extrusion   0 | </font><font color="#00D700">■</font><font color="#6C6C6C">         </font> │
│    │                     │          │  <font color="#6C6C6C"><i>en.</i></font>  <font color="#6C6C6C">           11:50:39</font>  │ <font color="#6C6C6C"> visualise_VE_VTK_1                  0 | </font><font color="#00D700">■</font><font color="#6C6C6C">         </font> │
│    │                     │          │                            │ <font color="#6C6C6C"> modify_VE_add_buffer_zones          0 | </font><font color="#00D700">■</font><font color="#6C6C6C">         </font> │
│    │                     │          │                            │ <font color="#6C6C6C"> visualise_VE_VTK_2                  0 | </font><font color="#00D700">■</font><font color="#6C6C6C">         </font> │
│    │                     │          │                            │ <font color="#6C6C6C"> simulate_VE_loading_damask          0 | </font><font color="#00D700">■■■■</font><font color="#D70000">E</font><font color="#FF8700">sss</font><font color="#6C6C6C">  </font> │
</pre>

```
cat execute/task_5_simulate_VE_loading_damask/e_0/r_0/stderr.log 
[0]PETSC ERROR: ------------------------------------------------------------------------
[0]PETSC ERROR: Caught signal number 11 SEGV: Segmentation Violation, probably memory access out of range
[0]PETSC ERROR: Try option -start_in_debugger or -on_error_attach_debugger
[0]PETSC ERROR: or see https://petsc.org/release/faq/#valgrind
[0]PETSC ERROR: or try http://valgrind.org on GNU/linux and Apple Mac OS X to find memory corruption errors
[0]PETSC ERROR: configure using --with-debugging=yes, recompile, link, and run 
[0]PETSC ERROR: to get more information on the crash.
[0]PETSC ERROR: --------------------- Error Message --------------------------------------------------------------
[0]PETSC ERROR: Signal received
[0]PETSC ERROR: See https://petsc.org/release/faq/ for trouble shooting.
[0]PETSC ERROR: Petsc Release Version 3.15.5, Sep 29, 2021 
[0]PETSC ERROR: /usr/bin/DAMASK_grid on a  named node604.pri.csf3.alces.network by mbexegc2 Thu Nov 28 11:51:48 2024
[0]PETSC ERROR: Configure options --build=x86_64-linux-gnu --prefix=/usr --includedir=${prefix}/include --mandir=${prefix}/share/man --infodir=${prefix}/share/info --sysconfdir=/etc --localstatedir=/var --with-option-checking=0 --with-silent-rules=0 --libdir=${prefix}/lib/x86_64-linux-gnu --runstatedir=/run --with-maintainer-mode=0 --with-dependency-tracking=0 --with-debugging=0 --shared-library-extension=_real --with-shared-libraries --with-pic=1 --with-cc=mpicc --with-cxx=mpicxx --with-fc=mpif90 --with-cxx-dialect=C++11 --with-opencl=1 --with-blas-lib=-lblas --with-lapack-lib=-llapack --with-scalapack=1 --with-scalapack-lib=-lscalapack-openmpi --with-ptscotch=1 --with-ptscotch-include=/usr/include/scotch --with-ptscotch-lib="-lptesmumps -lptscotch -lptscotcherr" --with-fftw=1 --with-fftw-include="[]" --with-fftw-lib="-lfftw3 -lfftw3_mpi" --with-yaml=1 --with-hdf5-include=/usr/include/hdf5/openmpi --with-hdf5-lib="-L/usr/lib/x86_64-linux-gnu/hdf5/openmpi -L/usr/lib/x86_64-linux-gnu/openmpi/lib -lhdf5 -lmpi" --CXX_LINKER_FLAGS=-Wl,--no-as-needed --with-hypre=1 --with-hypre-include=/usr/include/hypre --with-hypre-lib=-lHYPRE --with-mumps=1 --with-mumps-include="[]" --with-mumps-lib="-ldmumps -lzmumps -lsmumps -lcmumps -lmumps_common -lpord" --with-suitesparse=1 --with-suitesparse-include=/usr/include/suitesparse --with-suitesparse-lib="-lumfpack -lamd -lcholmod -lklu" --with-superlu=1 --with-superlu-include=/usr/include/superlu --with-superlu-lib=-lsuperlu --with-superlu_dist=1 --with-superlu_dist-include=/usr/include/superlu-dist --with-superlu_dist-lib=-lsuperlu_dist --with-ml=1 --with-ml-include=/usr/include/trilinos --with-ml-lib=-ltrilinos_ml --with-zoltan=1 --with-zoltan-include=/usr/include/trilinos --with-zoltan-lib=-ltrilinos_zoltan --prefix=/usr/lib/petscdir/petsc3.15/x86_64-linux-gnu-real --PETSC_ARCH=x86_64-linux-gnu-real CFLAGS="-g -O2 -ffile-prefix-map=/build/petsc-tFq6Xk/petsc-3.15.5+dfsg1=. -flto=auto -ffat-lto-objects -flto=auto -ffat-lto-objects -fstack-protector-strong -Wformat -Werror=format-security -fPIC" CXXFLAGS="-g -O2 -ffile-prefix-map=/build/petsc-tFq6Xk/petsc-3.15.5+dfsg1=. -flto=auto -ffat-lto-objects -flto=auto -ffat-lto-objects -fstack-protector-strong -Wformat -Werror=format-security -fPIC" FCFLAGS="-g -O2 -ffile-prefix-map=/build/petsc-tFq6Xk/petsc-3.15.5+dfsg1=. -flto=auto -ffat-lto-objects -flto=auto -ffat-lto-objects -fstack-protector-strong -fPIC -ffree-line-length-0" FFLAGS="-g -O2 -ffile-prefix-map=/build/petsc-tFq6Xk/petsc-3.15.5+dfsg1=. -flto=auto -ffat-lto-objects -flto=auto -ffat-lto-objects -fstack-protector-strong -fPIC -ffree-line-length-0" CPPFLAGS="-Wdate-time -D_FORTIFY_SOURCE=2" LDFLAGS="-Wl,-Bsymbolic-functions -flto=auto -ffat-lto-objects -flto=auto -Wl,-z,relro -fPIC" MAKEFLAGS=w
[0]PETSC ERROR: #1 User provided function() at unknown file:0
[0]PETSC ERROR: Run with -malloc_debug to check if memory corruption is causing the crash.
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 0 in communicator MPI_COMM_WORLD
with errorcode 59.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
```
which looks to be an out-of-memory error. 
@aplowman  I think this is where we got to on the call today, but now it's  clearer in my head :)
I think you suggested editing the demo workflow to request more cores in order to get more memory allocated for that part of the workflow?

I'll run the shared install of MatFlow after lunch and report what that does.

**Comment by gcapes** [comment]
Running the demo workflow using the shared install fails at the same point, with the same stderr.log error message about memory.

<pre>┌────┬──────────────────────────────────────┬──────────┬────────────────────────────┬─────────────────────────────────────────────────────┐
│<b> ID </b>│<b> Name                                 </b>│<b> Status   </b>│<b> Times                      </b>│<b> Actions                                             </b>│
├────┼──────────────────────────────────────┼──────────┼────────────────────────────┼─────────────────────────────────────────────────────┤
│ <font color="#6C6C6C">3 </font> │ <font color="#6C6C6C">RVE_extrusion_EBSD_2024-11-28_133327</font> │ <font color="#6C6C6C"><i>inactive</i></font> │  <font color="#6C6C6C"><i>sb.</i></font>  <font color="#6C6C6C">2024-11-28 13:33:30</font>  │ <font color="#6C6C6C"> load_microstructure_EBSD            0 | </font><font color="#00D700">■</font><font color="#6C6C6C">         </font> │
│    │                                      │          │  <font color="#6C6C6C"><i>st.</i></font>  <font color="#6C6C6C">           13:34:14</font>  │ <font color="#6C6C6C"> generate_volume_element_extrusion   0 | </font><font color="#00D700">■</font><font color="#6C6C6C">         </font> │
│    │                                      │          │  <font color="#6C6C6C"><i>en.</i></font>  <font color="#6C6C6C">           13:48:48</font>  │ <font color="#6C6C6C"> visualise_VE_VTK_1                  0 | </font><font color="#00D700">■</font><font color="#6C6C6C">         </font> │
│    │                                      │          │                            │ <font color="#6C6C6C"> modify_VE_add_buffer_zones          0 | </font><font color="#00D700">■</font><font color="#6C6C6C">         </font> │
│    │                                      │          │                            │ <font color="#6C6C6C"> visualise_VE_VTK_2                  0 | </font><font color="#00D700">■</font><font color="#6C6C6C">         </font> │
│    │                                      │          │                            │ <font color="#6C6C6C"> simulate_VE_loading_damask          0 | </font><font color="#00D700">■■■■</font><font color="#D70000">E</font><font color="#FF8700">sss</font><font color="#6C6C6C">  </font> │
│    │                                      │          │                            │                                                     │
└────┴──────────────────────────────────────┴──────────┴────────────────────────────┴─────────────────────────────────────────────────────┘
</pre>

I'm now going to try each of these again, first modifying the task to request 2 cores.

**Comment by gcapes** [comment]
Currently running with matflow-dev. I think running workflows with this version will prevent `maflow show` working correctly afterwards with the latest matflow? Is that correct? Is the simplest approach just to let the `matflow-dev` workflow complete, clear known subs, then submit the workflow with the newer matflow such that `matflow show` will work? @aplowman

**Comment by gcapes** [comment]
Using 
```
  - schema: simulate_VE_loading_damask
    resources:
      main:
        num_cores: 2
      output_file_parser:
        num_cores: 2
```
gets rid of the MPI memory error, but the workflow still doesn't complete.
<pre>┌────┬─────────────────────────────────────────────────────────────────────────────┬──────────┬────────────────────────────┬─────────────────────────────────────────────────────┐
│<b> ID </b>│<b> Name                                                                        </b>│<b> Status   </b>│<b> Times                      </b>│<b> Actions                                             </b>│
├────┼─────────────────────────────────────────────────────────────────────────────┼──────────┼────────────────────────────┼─────────────────────────────────────────────────────┤
│ <font color="#6C6C6C">4 </font> │ <font color="#6C6C6C">matflow_dev_2_cores                                                        </font> │ <font color="#6C6C6C"><i>inactive</i></font> │  <font color="#6C6C6C"><i>sb.</i></font>  <font color="#6C6C6C">2024-11-28 13:59:48</font>  │ <font color="#6C6C6C"> load_microstructure_EBSD            0 | </font><font color="#00D700">■</font><font color="#6C6C6C">         </font> │
│    │                                                                             │          │  <font color="#6C6C6C"><i>st.</i></font>  <font color="#6C6C6C">           14:00:30</font>  │ <font color="#6C6C6C"> generate_volume_element_extrusion   0 | </font><font color="#00D700">■</font><font color="#6C6C6C">         </font> │
│    │                                                                             │          │  <font color="#6C6C6C"><i>en.</i></font>  <font color="#6C6C6C">           14:10:03</font>  │ <font color="#6C6C6C"> visualise_VE_VTK_1                  0 | </font><font color="#00D700">■</font><font color="#6C6C6C">         </font> │
│    │                                                                             │          │                            │ <font color="#6C6C6C"> modify_VE_add_buffer_zones          0 | </font><font color="#00D700">■</font><font color="#6C6C6C">         </font> │
│    │                                                                             │          │                            │ <font color="#6C6C6C"> visualise_VE_VTK_2                  0 | </font><font color="#00D700">■</font><font color="#6C6C6C">         </font> │
│    │                                                                             │          │                            │ <font color="#6C6C6C"> simulate_VE_loading_damask          0 | </font><font color="#00D700">■■■■</font><font color="#0087FF">●</font><font color="#767676">...</font><font color="#6C6C6C">  </font> │
</pre>

There's nothing in `RVE_extrusion_EBSD_2024-11-28_133327/execute/task_5_simulate_VE_loading_damask/e_0/r_0/stderr.log`, or the SGE std err file in `artifacts`. Confusingly, `qacct` shows that this job ran on the serial queue (even though 2 cores were requested)?
```
qacct -j 5309975
==============================================================
qname        serial.q            
hostname     node606.pri.csf3.alces.network
group        support             
owner        mbexegc2            
project      support.prj         
department   defaultdepartment   
jobname      js_0.sh             
jobnumber    5309975             
taskid       undefined
account      sge                 
priority     0                   
qsub_time    Thu Nov 28 13:33:30 2024
start_time   Thu Nov 28 13:33:32 2024
end_time     Thu Nov 28 13:49:25 2024
granted_pe   NONE                
slots        1                   
failed       0    
exit_status  0                   
ru_wallclock 953s
ru_utime     391.136s
ru_stime     51.882s
ru_maxrss    7.697MB
ru_ixrss     0.000B
ru_ismrss    0.000B
ru_idrss     0.000B
ru_isrss     0.000B
ru_minflt    7127035             
ru_majflt    1796                
ru_nswap     0                   
ru_inblock   1496856             
ru_oublock   18589408            
ru_msgsnd    0                   
ru_msgrcv    0                   
ru_nsignals  0                   
ru_nvcsw     252144              
ru_nivcsw    36080               
cpu          443.017s
mem          675.714GBs
io           29.670GB
iow          0.000s
maxvmem      7.729GB
arid         undefined
ar_sub_time  undefined
category     -u mbexegc2
```

**Comment by gcapes** [comment]
I'm not sure what's going on or what to try next. 
@aplowman

**Comment by gcapes** [comment]
While investigating https://github.com/hpcflow/matflow-new/issues/266 I've got a similar situation, and though the jobs haven't finished yet, they have been going ~9 hours already (is a demo workflow supposed to take that long?).
<pre>┌────┬─────────────────────────────────────┬────────┬────────────────────────────┬─────────────────────────────────────────────────────┐
│<b> ID </b>│<b> Name                                </b>│<b> Status </b>│<b> Times                      </b>│<b> Actions                                             </b>│
├────┼─────────────────────────────────────┼────────┼────────────────────────────┼─────────────────────────────────────────────────────┤
│ 0  │ latest_versions_2cores_keepdimstrue │ <font color="#0087FF">●</font>/<font color="#767676">◊</font>    │  <i>sb.</i>  2024-12-02 09:53:43  │  load_microstructure_EBSD            0 | <font color="#00D700">■</font>          │
│    │                                     │        │  <i>st.</i>             09:53:45  │  generate_volume_element_extrusion   0 | <font color="#00D700">■</font>          │
│    │                                     │        │  <i>en.</i>             09:55:48  │  visualise_VE_VTK_1                  0 | <font color="#00D700">■</font>          │
│    │                                     │        │                            │  modify_VE_add_buffer_zones          0 | <font color="#00D700">■</font>          │
│    │                                     │        │                            │  visualise_VE_VTK_2                  0 | <font color="#00D700">■</font>          │
│    │                                     │        │                            │  simulate_VE_loading_damask          0 | <font color="#00D700">■■■■</font><font color="#0087FF">●</font><font color="#767676">...</font>   │
│    │                                     │        │                            │                                                     │
</pre>

**Comment by gcapes** [comment]
Try 12 cores - the demo workflow can be split into 12

**Comment by gcapes** [comment]
Great success!

<pre>┌────┬─────────────────────────────────────┬──────────┬────────────────────────────┬─────────────────────────────────────────────────────┐
│<b> ID </b>│<b> Name                                </b>│<b> Status   </b>│<b> Times                      </b>│<b> Actions                                             </b>│
├────┼─────────────────────────────────────┼──────────┼────────────────────────────┼─────────────────────────────────────────────────────┤
│ <font color="#6C6C6C">1 </font> │ <font color="#6C6C6C">latest_versions_keep_dims_12cores  </font> │ <font color="#6C6C6C"><i>inactive</i></font> │  <font color="#6C6C6C"><i>sb.</i></font>  <font color="#6C6C6C">2024-12-05 10:42:21</font>  │ <font color="#6C6C6C"> load_microstructure_EBSD            0 | </font><font color="#00D700">■</font><font color="#6C6C6C">         </font> │
│    │                                     │          │  <font color="#6C6C6C"><i>st.</i></font>  <font color="#6C6C6C">           10:42:32</font>  │ <font color="#6C6C6C"> generate_volume_element_extrusion   0 | </font><font color="#00D700">■</font><font color="#6C6C6C">         </font> │
│    │                                     │          │  <font color="#6C6C6C"><i>en.</i></font>  <font color="#6C6C6C">           10:46:33</font>  │ <font color="#6C6C6C"> visualise_VE_VTK_1                  0 | </font><font color="#00D700">■</font><font color="#6C6C6C">         </font> │
│    │                                     │          │                            │ <font color="#6C6C6C"> modify_VE_add_buffer_zones          0 | </font><font color="#00D700">■</font><font color="#6C6C6C">         </font> │
│    │                                     │          │                            │ <font color="#6C6C6C"> visualise_VE_VTK_2                  0 | </font><font color="#00D700">■</font><font color="#6C6C6C">         </font> │
│    │                                     │          │                            │ <font color="#6C6C6C"> simulate_VE_loading_damask          0 | </font><font color="#00D700">■■■■■■■■</font><font color="#6C6C6C">  </font> │
</pre>
