### ISSUE TITLE
Software review for end of project report

### ISSUE THREAD

**Issue by gcapes** [LightForm-group/non-repo-issues#8]
- [x] 1 page of descriptions of various software packages produced by the group.
- [x] Joao to send a list of repos

Dead line end of Sept

**Comment by gcapes** [comment]
The task is to go through the links, and 

- [x] write 3 lines about what each piece of software does, based on its github repo
- [x] Estimate the reusability status of each piece of software.

The aim is to show that research outputs from the group are not just papers but also tools, and that this can only be done with RSE support.
Research in the group is computationally intensive, but without sharing code, you're not really sharing any knowledge of how to repeat the analysis.

**Comment by JQFonseca** [comment]
Software packages associated with LightForm:

-  [MatFlow](https://github.com/LightForm-group/matflow) Maybe there is a newer page? Check with Adam. Also ask about extensions. Are these collected somewhere else now? 
-  [xrdfit](https://github.com/LightForm-group/xrdfit)
- [KWN-deformation](https://github.com/LightForm-group/KWN-deformation)
- [Continuous peak fit](https://github.com/LightForm-group/continuous-peak-fit-analysis)
- [strain localization criteria](https://github.com/LightForm-group/strain-localisation-criteria)
- [data light](https://github.com/LightForm-group/datalight)
- [Phase field pre-processor](https://github.com/LightForm-group/phase-field-pre-processor)
- [Beta reconstruction in Python](https://github.com/LightForm-group/beta-reconstruction)
- [DefDap](https://github.com/MechMicroMan/DefDAP)

There is also a number of other bits of analysis software and notebooks - just point to the general repository.

**Comment by gcapes** [comment]
Emailed to @JQFonseca  on Weds for feedback

**Comment by aplowman** [comment]
[phase-field-pre-processor](https://github.com/LightForm-group/phase-field-pre-processor) is superseded by [cipher-parse](https://github.com/LightForm-group/cipher-parse)

There's also [damask-parse](https://github.com/LightForm-group/damask-parse). These packages are for pre- and post-processing CIPHER/DAMASK simulations.

There is also [formable](https://github.com/LightForm-group/formable), for fitting yield functions and single-crystal parameters.

**Comment by gcapes** [comment]
Thanks Adam. Now included too, and dropped phase-field-pre-processor instead.

**Comment by JQFonseca** [comment]
Anything else you think we should add, Adam?

João

**Comment by aplowman** [comment]
I think the Wiki is notable as software-related. It's been quite successful I would say, with fairly frequent contributions. https://github.com/LightForm-group/wiki
