### ISSUE TITLE
Install Mtex on Apple M1 laptop

### ISSUE THREAD

**Issue by gcapes** [LightForm-group/non-repo-issues#9]
I've been helping Yuchen install Mtex in his new apple laptop.

We have been following the [guide](https://mtex-toolbox.github.io/installation) and have most of the libraries installed under homebrew, but can't get NFFT installed. It seems that the suggested configure option `--with-apple-gcc-arch=x86_64` isn't a valid option (we changed the value to `arm64`, and I tried using the recognised option `--with-gcc-arch` but that didn't work either.

It seems others have had this problem and [this comment] (https://github.com/mtex-toolbox/mtex/discussions/1285#discussioncomment-1804649) pretty much describes the situation.

Three things in that issue that I'm not sure we've not yet tried are 
- [x] [Using a MATLAB version which will run natively on the M1](https://github.com/mtex-toolbox/mtex/discussions/1285#discussioncomment-5105969)
  Yuchen is using R2023a, which needs to use Rosetta. The R2023b prerelease runs natively. 
https://uk.mathworks.com/support/requirements/apple-silicon.html
Using R2023b gives the same error message when trying to set up mtex:
   ```
  MTEX: Error running NFFT with openMP - I'm going to try it without openmp!
   
    MTEX: Error running NFFT without openMP!
     
   I did not get NFFT working. This restricts the functionality of MTEX.
   To overcome this restriction you may need to compile the NFFT your own.
   Please have a look at https://mtex-toolbox.github.io/installation for possible workarounds
   or ask in the forum https://github.com/mtex-toolbox/mtex/discussions for help.
   
    The original error message was:
   
  Undefined function 'nfsftmex' for input arguments of type 'char'.
  
  Error in S2FunHarmonic.quadrature (line 77)
    nfsftmex('precompute', bw, 1000, 1, 0);
  
  Error in check_installation>check_NFSFT (line 83)
    sF = S2FunHarmonic.quadrature(f,'bandwidth',12);
  
  Error in check_installation (line 53)
    check_NFSFT
  
  Error in startup_mtex (line 69)
  check_installation;
   ```
- [x] [Copy files from here](https://github.com/mtex-toolbox/mtex/discussions/1285#discussioncomment-1793753) and put the required ones in the Mtex folder (I think we just downloaded the files, and failed to get the [simple_test.m](https://www-user.tu-chemnitz.de/~potts/nfft/download.php#matlab) script to run without errors. It might be that copying the required files to the mtex directory is what we should do instead
  ```
    Unrecognized function or variable 'nfftmex'.
  
  Error in nfft_get_num_threads (line 21)
  nthreads = nfftmex('get_num_threads');
  
  Error in simple_test (line 21)
  fprintf('Number of threads: %d\n\n', nfft_get_num_threads());
  ```
- [x] Drop the `--with-matlab` option as suggested at the end of [this comment](https://github.com/mtex-toolbox/mtex/discussions/1285#discussioncomment-1804649)
  This runs through without errors, but the linking step (5) fails, so I guess this means it just compiled NFFT without making mex files

However, perhaps the first thing to try might be 

- [x] using the standard options when running `./configure` (including `--enable-openmp`), per [my comment](https://github.com/LightForm-group/non-repo-issues/issues/9#issuecomment-1717530076) below
  Adding this option gives the error `configure: error: You don't seem to have the threaded FFTW 3 library installed.`

**Comment by JQFonseca** [comment]
Michael ***@***.***) might be able to help.

João

**Comment by mikesmic** [comment]
I remember having some issues with NFFT. It is bundled with mtex but I had to change some file names round or maybe force it to compile in a different way. This was 2-3 years ago though and I can't remember exactly. I will have a look at my install and get back to you probably on Friday

**Comment by gcapes** [comment]
Thanks both. That was a good clue - NFFT mex files come with mtex, but these are for use with openmp. I'm not really very familiar with openMP or MPI, but I thought this wasn't the option to use on a laptop. I guess MPI is for multi-node applications, and OpenMP can be used on a single machine? In this case, it might be worth running `./configure` with the standard set of options i.e. including `--enable-openmp`, which might force it to use the NFFT mex files provided. I'll add this as a check box option above.

**Comment by gcapes** [comment]
@cjfullerton 
Perhaps you could do a test install on your Mac?

**Comment by YuchenZZheng** [comment]
The problem with my MTEX finally solved by reinstalling Matlab 2023a, I've tried this method before, but this time I repeated running 'startup_mtex' again and again, approved all the report windows jumped out. It is du to the Privacy & Security function of MacOS, a lot of files are recognised 'failed to verified' which you have to approval manually in system preferences. To approve them all needs 3-4 times of startup run and do remember to press 'open' to last couple of pop-up notifications ( the Matlab crashed after pressing 'open' for my first installation, but seems fine after I reinstalled the Matlab, that is tricky ). 

The fact is even now I still cannot compile NFFT on my laptop, however no error comes from the Matlab and MTEX, which means the installation of NFFT is not compulsory when using MTEX. 

I followed the instruction from https://mtex-toolbox.github.io/installation to solve 'Unable to compile mex files during startup_mtex' earlier, which should also contribute to solving the problems.

**Comment by gcapes** [comment]
Glad you got it sorted, despite the best efforts of macOS :)
